from enum import Enum, unique, auto

@unique
class CallbackEnum(Enum):
    # student replies
    STUDENT = auto()
    SAVE_CLASS = auto()
    NOT_SAVE_CLASS = auto()
    PARALLEL = auto()
    LETTER = auto()
    CONFIRM_SUBCLASS = auto()
    CHANGE_SUBCLASS = auto()
    # teacher replies
    TEACHER = auto()
    SAVE_NAME = auto()
    NOT_SAVE_NAME = auto()
    CONFIRM_NAME = auto()
    CHANGE_NAME = auto()
    # main menu
    CHECK_NEXT_LESSON = auto()
    CHECK_WEEKS = auto()
    CHECK_TODAY = auto()
    CHECK_TOMORROW = auto()
    CHECK_CERTAIN_DAY = auto()
    MISC_MENU = auto()
    # misc menu
    FIND_SUBCLASS = auto()
    FIND_TEACHER = auto()
    ANNOUNCEMENTS = auto()
    HELPFUL_LINKS = auto()
    HELP = auto()
    CHANGE_INFORMATION = auto()
    # find class
    FIND_SUBCLASS_NOW = auto()
    FIND_SUBCLASS_NEXT_LESSON = auto()
    FIND_SUBCLASS_TODAY = auto()
    FIND_SUBCLASS_WEEK = auto()
    FIND_SUBCLASS_CERTAIN_DAY = auto()
    # find teacher
    FIND_TEACHER_NOW = auto() 
    FIND_TEACHER_NEXT_LESSON = auto()
    FIND_TEACHER_TODAY = auto()
    FIND_TEACHER_WEEK = auto()
    FIND_TEACHER_CERTAIN_DAY = auto()
    # help menu
    TECHNICAL_SUPPORT_AUTO = auto()
    TUTORIALS = auto()
    EXAMPLES = auto()
    FAQ = auto()