# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: stop docker container
        run: |
          docker stop $(docker ps -a --filter=name=skedule-telegram --format="{{.ID}}");

      - name: remove docker container
        run: |
          docker rm $(docker ps -a --filter=name=skedule-telegram --format="{{.ID}}");

      - name: remove docker images
        run: |
          docker image rm $(docker images --filter=reference=skedule-telegram --format "{{.ID}}");
      

      - name: build docker container
        run: |
          docker build -t skedule-telegram .;
      
      - name: start docker container
        run: |
          docker run -d --name skedule-telegram skedule-telegram
