# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2



      # Runs a set of commands using the runners shell
      - name: deploy
        run: |
          cp /.properties .

          if [[ $(cat switch_profile) == "users" ]];
            then export dockername="skedule-telegram";
            else export dockername="skedule-telegram-debug";
          fi

          echo $dockername;


          if [[ $(docker ps -a --filter=name=$dockername --format="{{.ID}}") ]]
            then docker stop $(docker ps -a --filter=name=$dockername --format="{{.ID}}");
          fi

          if [[ $(docker ps -a --filter=name=$dockername --format="{{.ID}}") ]]
            then docker rm $(docker ps -a --filter=name=$dockername --format="{{.ID}}");
          fi

          if [[ $(docker images --filter=reference=$dockername --format="{{.ID}}") ]]
            then docker image rm $(docker images --filter=reference=$dockername --format "{{.ID}}");
          fi


          docker build -t $dockername .;
          docker run -d --name $dockername $dockername;